version: '3.8'

services:
  backend:
    build: ./back
    container_name: music_backend
    ports:
      - "8000:8000"
    networks:
      - music_network
    restart: always

  frontend:
    build: ./front
    container_name: music_frontend
    ports:
      - "8501:8501"
    networks:
      - music_network
    restart: always
    depends_on:
      - backend

networks:
  music_network:
    driver: bridge